name: extract-tools

on:
  schedule:
  # Run at 00:42 every day
    - cron:  '42 0 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  extract-tools:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Extract HDR UK Gateway Tools
        env:
          DATABASE: ${{ secrets.DATABASE }}
          DATABASE_CONN_URI: ${{ secrets.DATABASE_CONN_URI }}
        run: python3 scripts/extract-tools.py
      
      - name: Commit extracts to master branch
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          commit_message: Commit new tools
          branch: ${{ github.head_ref }}
          commit_user_name: Susheel Varma
          commit_user_email: susheel.varma@hdruk.ac.uk
          commit_author: Susheel Varma <susheel.varma@hdruk.ac.uk>